// Generated by CoffeeScript 1.3.3
(function() {

  $(function() {
    data.initialize();
    return navigation.initialize();
  });

  window.data = {
    initialize: function() {
      this.screeningOverviewTemplateMarkup = $("#screening-overview-template").html().replace(/[\t\n\r]/g, '');
      this.screeningDetailTemplateMarkup = $("#screening-detail-template").html().replace(/[\t\n\r]/g, '');
      return this.addScreenings();
    },
    addScreenings: function() {
      var screening, _i, _len, _ref, _results;
      this.parseScreeningData();
      _ref = this.screenings;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        screening = _ref[_i];
        $("#screening-overview-wrapper").append(this.screeningOverviewTemplate(screening));
        _results.push($("#content").append(this.screeningDetailTemplate(screening)));
      }
      return _results;
    },
    parseScreeningData: function() {
      var id, screening, _results;
      this.screenings = [];
      _results = [];
      for (screening in screeningData) {
        id = screening;
        screening = screeningData[screening];
        screening.id = id;
        screening.waffle.name = this.getWaffleName(screening.waffle);
        screening.drink.name = this.getDrinkName(screening.drink);
        _results.push(this.screenings.push({
          screening: screening
        }));
      }
      return _results;
    },
    screeningOverviewTemplate: function(screening) {
      return _.template(this.screeningOverviewTemplateMarkup, screening);
    },
    screeningDetailTemplate: function(screening) {
      return _.template(this.screeningDetailTemplateMarkup, screening);
    },
    getWaffleName: function(waffle) {
      return "" + waffle.base + " waffles";
    },
    getDrinkName: function(drink) {
      if (drink.name != null) {
        return drink.name;
      } else {
        return "" + drink.base + " drinking vinegar";
      }
    }
  };

  window.navigation = {
    initialize: function() {
      return this.loadInitialContent();
    },
    getIdFromClick: function(e) {
      return $(e.currentTarget).data("id");
    },
    showScreeningDetail: function(id) {
      $("#screening-overview-wrapper").hide();
      return $(".screening-detail[data-id=" + id + "]").fadeIn();
    },
    showScreeningOverview: function() {
      $(".screening-detail").hide();
      return $("#screening-overview-wrapper").fadeIn();
    },
    loadInitialContent: function() {
      var params;
      params = this.getParams();
      if ((params.id != null) && this.isValidId(params.id)) {
        return this.showScreeningDetail(params.id);
      } else {
        return this.showScreeningOverview();
      }
    },
    getParams: function() {
      var param, params, res, _i, _len, _ref;
      res = {};
      params = window.location.search.replace(/^\?/, "");
      _ref = params.split("&");
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        param = _ref[_i];
        param = param.split("=");
        res[param[0]] = param[1];
      }
      return res;
    },
    isValidId: function(id) {
      return _.contains(_.keys(screeningData), id);
    }
  };

}).call(this);
