// Generated by CoffeeScript 1.6.3
(function() {
  var emmm;

  $(function() {
    return emmm.init();
  });

  emmm = {
    init: function() {
      this.eventTemplateMarkup = $("#event-overview-template").html().replace(/[\t\n\r]/g, '');
      return this.addEvents();
    },
    addEvents: function() {
      var event, _i, _len, _ref, _results;
      this.parseEventData();
      _ref = this.events;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        event = _ref[_i];
        _results.push($("#event-overview-wrapper").append(this.eventTemplate(event)));
      }
      return _results;
    },
    parseEventData: function() {
      var drink, event, _results;
      this.events = [];
      _results = [];
      for (event in eventData) {
        event = eventData[event];
        if (event.drink.name != null) {
          drink = event.drink.name;
        } else {
          drink = "" + event.drink.base + " drinking vinegar";
        }
        _results.push(this.events.push({
          movie: event.movie.title,
          waffle: "" + event.waffle.base + " waffles",
          drink: drink
        }));
      }
      return _results;
    },
    eventTemplate: function(data) {
      return _.template(this.eventTemplateMarkup, data);
    }
  };

}).call(this);
